/**
    날짜 : 2023/10/02
    이름 : 이현정
    내용 : 1장 데이터베이스와 DBMS 개요
*/

--실습하기 1-1. 데이터베이스 생성(사용자 생성)


--실습하기 1-2. NUMBER 자료형 실습
CREATE TABLE TYPE_TEST_NUMBER (
    num1 NUMBER,
    num2 NUMBER(2),
    num3 NUMBER(3,1),
    num4 NUMBER(4,2),
    num5 NUMBER(5,6)
);

--num1 NUMBER
INSERT INTO TYPE_TEST_NUMBER (num1) VALUES (1);
INSERT INTO TYPE_TEST_NUMBER (num1) VALUES (123);
INSERT INTO TYPE_TEST_NUMBER (num1) VALUES (123.74);
INSERT INTO TYPE_TEST_NUMBER (num1) VALUES (123.12345);

--num2 NUMBER(2)
INSERT INTO TYPE_TEST_NUMBER (num2) VALUES (12);
INSERT INTO TYPE_TEST_NUMBER (num2) VALUES (123); 
INSERT INTO TYPE_TEST_NUMBER (num2) VALUES (1.2);
INSERT INTO TYPE_TEST_NUMBER (num2) VALUES (1.23);
INSERT INTO TYPE_TEST_NUMBER (num2) VALUES (12.34567);
INSERT INTO TYPE_TEST_NUMBER (num2) VALUES (12.56789);
INSERT INTO TYPE_TEST_NUMBER (num2) VALUES (123.56789);

--num3 NUMBER(3,1)
INSERT INTO TYPE_TEST_NUMBER (num3) VALUES (12);
INSERT INTO TYPE_TEST_NUMBER (num3) VALUES (123);--소수점자리를 만족시키지 못하기에 Error
INSERT INTO TYPE_TEST_NUMBER (num3) VALUES (12.1);
INSERT INTO TYPE_TEST_NUMBER (num3) VALUES (12.1234);
INSERT INTO TYPE_TEST_NUMBER (num3) VALUES (12.56789);
INSERT INTO TYPE_TEST_NUMBER (num3) VALUES (123.56789); --유효자리수가 3인데 정수부 3자리 + 실수부1자리 때문에 Error

--실습하기 1-3. 문자형 자료형 실습
CREATE TABLE TYPE_TEST_CHAR (
     char1 CHAR(1), -- 고정형
     char2 CHAR(2), --길이가 1byte = 문자의 길이가 2개 
     char3 CHAR(3),
     vchar1 VARCHAR2(1), -- 가변형
     vchar2 VARCHAR2(2),
     vchar3 VARCHAR2(3),
     nvchar1 NVARCHAR2(1), -- 가변형 (NVARCHAR: 아시아권 모든 문자 포함)
     nvchar2 NVARCHAR2(2),
     nvchar3 NVARCHAR2(3)
);

--CHAR
INSERT INTO TYPE_TEST_CHAR (char1) VALUES ('A');
INSERT INTO TYPE_TEST_CHAR (char1) VALUES ('가');
INSERT INTO TYPE_TEST_CHAR (char2) VALUES ('ABC');
INSERT INTO TYPE_TEST_CHAR (char2) VALUES ('가나다');


--VARCHAR2
INSERT INTO TYPE_TEST_CHAR (vchar1) VALUES ('A');
INSERT INTO TYPE_TEST_CHAR (vchar2) VALUES ('AB');
INSERT INTO TYPE_TEST_CHAR (vchar3) VALUES ('가');

--NVARCHAR2
INSERT INTO TYPE_TEST_CHAR (nvchar1) VALUES ('A');
INSERT INTO TYPE_TEST_CHAR (nvchar2) VALUES ('AB');
INSERT INTO TYPE_TEST_CHAR (nvchar3) VALUES ('가나다');




